### ISSUE TITLE
DLC'ler eksik.

### ISSUE THREAD

**Issue by wasabi1232** [0xANTI/0xANTI-Releases#1]
Verdiğiniz her iki AC Odyssey dosyasında da DLC çevirileri yok. Oyuna dosyalar ekleniyor ama çeviri yok. Hala ingilizce. Bilginize.

**Comment by 0xANTI** [comment]
AC Odyssey (Tam Sürüm) + 2 DLC (1.5.3) isimli olan dosyada DLC çevirileri dahil durumdadır. Oyunun güncel sürüm olduğundan ve farklı bir yama kurmadığınızdan emin olun.  Oyun klasöründe dlc_13 , dlc_34 ve dlc_44 klasörleri de olmalıdır. Yamayı kurarken herhangi bir hata mesajı almamanız gerekiyor.

**Comment by wasabi1232** [comment]
Hata mesajı almadım. Kuruldu dedi. Dediğiniz klasörlere baktım. .bak dosyaları vardı. O dosyaların ".bak"ını silip çalıştırdım oyunu. Oyun açıldı ama DLC çevirisi yoktu. Acaba TR yamanın yapıldığı ".forge"li dosyaları paylaşabilir misiniz? Kurulum programıyla da uğraşmayız.

**Comment by 0xANTI** [comment]
Herhangi bir sorun görünmüyor. Oyunun güncel sürüm (1.5.3) olduğundan emin ol. Xatab/fitgirl repackları üzerinde yama denendi. 3. DLC TR yamaya dahil değil, siz belki çevrilmemiş yamayı oynuyor olabilirsiniz.

Ekran görüntüleri:
https://ibb.co/Bc9XnL2
https://ibb.co/J7KN00v
https://ibb.co/QFPWk20

**Comment by GojiraTai** [comment]
Yamada sıkıntı yok, fitgirl sürümü mevcut bende, dosyaları oraya atıp yönetici olarak çalıştırınca yamayı kuruyor. Hepinize teşekkür ederim.

Wolfenstein-Youngblood'u da yükleyecekmisiniz? Yükleyecekseniz tahmini ne zamana yüklersiniz.

**Comment by 0xANTI** [comment]
> Yamada sıkıntı yok, fitgirl sürümü mevcut bende, dosyaları oraya atıp yönetici olarak çalıştırınca yamayı kuruyor. Hepinize teşekkür ederim.
> 
> Wolfenstein-Youngblood'u da yükleyecekmisiniz? Yükleyecekseniz tahmini ne zamana yüklersiniz.

0XANTI#2675
DC'den bana ulaşır mısınız?

**Comment by wasabi1232** [comment]
Merhaba. Acaba sizin için sıkıntı olmazsa ilgili ".forge" dosyalarını upload eder misiniz? Böylece önceden Türkçe Yama kuranlar da sıkıntı yaşamaz. Setup programları her zaman düzgün çalışmayabiliyor. Şimdiden teşekkürler.

**Comment by 0xANTI** [comment]
> Merhaba. Acaba sizin için sıkıntı olmazsa ilgili ".forge" dosyalarını upload eder misiniz? Böylece önceden Türkçe Yama kuranlar da sıkıntı yaşamaz. Setup programları her zaman düzgün çalışmayabiliyor. Şimdiden teşekkürler.
> 
> Bu arada ben de fitgirl sürümünü kullanıyorum. Oyunu silip tekrar kurmak 6-7 saat alıyor maalesef. O yüzden böyle bir şey istedim.

Yama boyutları yüksek olacağı için bu yolu tercih etmedim.
Upload hızımda biraz sıkıntı var bu nedenle dosyaları upload etmem çok uzun zaman alır.

Yamayı uygulayan bir arkadaş aşağıdaki dosyaları toplu olarak upload ederse uyumlu olacaktır.

DataPC_patch_01.forge
dlc_13/DataPC_13_dlc.forge
dlc_34/DataPC_34_dlc.forge
dlc_44/DataPC_44_dlc.forge

**Comment by wasabi1232** [comment]
Dosyaları biraz kurcaladım ve sanırım oldu. Çok teşekkürler.

**Comment by 0xANTI** [comment]
> Dosyaları biraz kurcaladım ve sanırım oldu. Çok teşekkürler.

Rica ederim.

Bu arada elinde orjinal Wolfenstein Youngblood olan varsa bana DC üzerinden ulaşması halinde yama testi yapabiliriz. Yama sadece orj. desteklediği için cracklı oyuna uyumlu değil.
